# Generated by Django 5.2.9 on 2026-01-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customnoveluser_model',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
