# Generated by Django 5.2.9 on 2026-01-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0002_remove_customnoveluser_model_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnoveluser_model',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customnoveluser_model',
            name='favourite',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
