# Generated by Django 5.2.9 on 2026-01-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0003_customnoveluser_model_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
