# Generated by Django 5.2.9 on 2026-01-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0004_alter_customnoveluser_model_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnoveluser_model',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
    ]
