# Generated by Django 5.2.9 on 2026-01-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0005_customnoveluser_model_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customnoveluser_model',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='customnoveluser_model',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='customnoveluser_model',
            name='liked_novels',
        ),
    ]
