# Generated by Django 5.2.9 on 2026-01-11 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0006_remove_customnoveluser_model_bookmarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyUsage_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_creation_requests_made', models.IntegerField(default=0)),
                ('next_reset_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
