# Generated by Django 5.2.9 on 2026-01-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0007_userdailyusage_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyusage_model',
            name='next_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
