# Generated by Django 5.2.9 on 2026-01-11 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0008_alter_userdailyusage_model_next_reset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyusage_model',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL),
        ),
    ]
