# Generated by Django 5.2.9 on 2026-01-17 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0009_alter_userdailyusage_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnoveluser_model',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customnoveluser_model',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='avatar',
            field=models.URLField(blank=True),
        ),
    ]
