# Generated by Django 5.2.9 on 2026-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0010_customnoveluser_model_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customnoveluser_model',
            name='name',
        ),
        migrations.AddField(
            model_name='customnoveluser_model',
            name='user_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
