# Generated by Django 5.2.9 on 2026-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0011_remove_customnoveluser_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
