# Generated by Django 5.2.9 on 2026-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0013_alter_customnoveluser_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
