# Generated by Django 5.2.9 on 2026-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0014_alter_customnoveluser_model_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='user_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
