# Generated by Django 5.2.9 on 2026-01-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0015_alter_customnoveluser_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customnoveluser_model',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
