# Generated by Django 5.2.9 on 2026-01-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0016_alter_customnoveluser_model_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customnoveluser_model',
            managers=[
            ],
        ),
    ]
