# Generated by Django 5.2.9 on 2026-01-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_Content_Generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterbeingcreated',
            name='chapter_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chapterbeingcreated',
            name='chapter_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chapterbeingcreated',
            name='ultra_short_summary',
            field=models.CharField(default='', max_length=512),
        ),
    ]
