# Generated by Django 5.2.9 on 2025-12-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novel_image',
            field=models.ImageField(blank=True, upload_to='novel_images/'),
        ),
    ]
