# Generated by Django 5.2.9 on 2025-12-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0002_novel_novel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
