# Generated by Django 5.2.9 on 2025-12-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0003_chapter_chapter_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_no']},
        ),
        migrations.AddField(
            model_name='novel',
            name='style_guide',
            field=models.TextField(blank=True, help_text='POV, tense, prose style, tone rules'),
        ),
        migrations.CreateModel(
            name='Whole_Novel_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_chapter', models.PositiveIntegerField()),
                ('to_chapter', models.PositiveIntegerField()),
                ('summary', models.TextField(help_text='Ultra-compressed summary of chapters range')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_summary', to='Novel_Content.novel')),
            ],
        ),
        migrations.CreateModel(
            name='WorlRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField()),
                ('locations', models.TextField()),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_rules', to='Novel_Content.novel')),
            ],
        ),
    ]
