# Generated by Django 5.2.9 on 2025-12-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0004_alter_chapter_options_novel_style_guide_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorlRules',
            new_name='WorldRules',
        ),
    ]
