# Generated by Django 5.2.9 on 2025-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0005_rename_worlrules_worldrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldrules',
            name='locations',
            field=models.TextField(blank=True),
        ),
    ]
