# Generated by Django 5.2.9 on 2025-12-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0006_alter_worldrules_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='world_rules',
            field=models.CharField(blank=True),
        ),
        migrations.DeleteModel(
            name='WorldRules',
        ),
    ]
