# Generated by Django 5.2.9 on 2025-12-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0007_novel_world_rules_delete_worldrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
