# Generated by Django 5.2.9 on 2025-12-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0008_alter_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='current_chapter',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
