# Generated by Django 5.2.9 on 2025-12-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0009_novel_current_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_no',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
