# Generated by Django 5.2.9 on 2025-12-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0010_alter_chapter_chapter_no_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='ultra_short_story_till_now',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Whole_Novel_Summary',
        ),
    ]
