# Generated by Django 5.2.9 on 2025-12-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0011_novel_ultra_short_story_till_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='world_rules',
            field=models.TextField(blank=True),
        ),
    ]
