# Generated by Django 5.2.9 on 2025-12-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0012_alter_novel_world_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_no', 'related_novel']},
        ),
    ]
