# Generated by Django 5.2.9 on 2025-12-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0013_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['related_novel', 'chapter_no']},
        ),
    ]
