# Generated by Django 5.2.9 on 2025-12-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0014_alter_chapter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
