# Generated by Django 5.2.9 on 2026-01-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0017_alter_novel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='current_chapter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
