# Generated by Django 5.2.9 on 2026-01-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0018_alter_novel_current_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_summary',
            field=models.TextField(default=''),
        ),
    ]
