# Generated by Django 5.2.9 on 2026-01-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0019_alter_chapter_chapter_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='genre',
        ),
        migrations.AddField(
            model_name='novel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
