# Generated by Django 5.2.9 on 2026-01-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0021_genre_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(to='Novel_Content.genre'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(to='Novel_Content.tag'),
        ),
    ]
