# Generated by Django 5.2.9 on 2026-01-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0023_novelreaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NovelReaction',
        ),
    ]
