# Generated by Django 5.2.9 on 2026-01-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0024_delete_novelreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
