# Generated by Django 5.2.9 on 2026-01-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0026_userlikes_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='novel_image',
        ),
    ]
