# Generated by Django 5.2.9 on 2026-01-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0027_remove_novel_novel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='nove_image',
            field=models.URLField(blank=True),
        ),
    ]
