# Generated by Django 5.2.9 on 2026-01-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Novel_Content', '0028_novel_nove_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='nove_image',
            new_name='novel_image',
        ),
    ]
