# Generated by Django 5.2.9 on 2026-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='weight',
            field=models.FloatField(),
        ),
    ]
