# Generated by Django 5.2.9 on 2025-12-28 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='free', max_length=50, unique=True)),
                ('plan_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interval', models.IntegerField(default=1)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('group', models.ManyToManyField(blank=True, related_name='plans', to='auth.group')),
            ],
            options={
                'permissions': [('premium_plan', 'Gets premium features'), ('free_plan', 'Get Limited features Only')],
            },
        ),
        migrations.CreateModel(
            name='Usersubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_at', models.IntegerField(blank=True, null=True)),
                ('end_at', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
